update build files from sipx 4.6

diff --git a/config/revision-gen b/config/revision-gen
--- a/config/revision-gen
+++ b/config/revision-gen
@@ -13,5 +13,10 @@ if test -f ./tarball-revision; then
     cat ./tarball-revision
     exit
 fi
+VER_REV=`git describe --abbrev=4 --match="v${VERSION}" HEAD`
+if [ "$?" != "0" ]; then
+    echo "Could not find tag v$VERSION" 1>&2
+    exit 1
+fi
 echo "${VER_REV}" | sed -e 's/^v[0-9.]\+-//g' -e 's/-/./g'
 
